---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3
  - name: windows-2016
  - name: windows-2012r2

suites:
  - name: metricly-windows
    includes:
      - windows-2016
      - windows-2012r2
    run_list:
      - recipe[metricly::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      metricly:
        install_flavor: windows
        windows_api_key: 123456789
  - name: metricly-linux
    includes:
      - ubuntu-16.04
      - centos-7.3
    run_list:
      - recipe[metricly::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      metricly:
        install_flavor: linux
        windows_api_key: 123456789
