---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3
  - name: windows-2016
  - name: windows-2012r2

suites:
  - name: metricly
    run_list:
      - recipe[metricly::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      metricly:
        windows_api_key: 123456789
        linux_api_key: 987654321
